name: turnstile_admin
description: "A new Flutter project."


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  path_provider: ^2.1.3
  url_launcher: ^6.2.6
  flutter_localizations:
    sdk: flutter
  provider: ^5.0.0

  qr_code_scanner: ^1.0.1
  http: ^1.2.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  pie_chart: ^5.4.0
  percent_indicator: ^4.2.3
  file_picker: ^8.0.2
  open_file: ^3.3.2
  intl: ^0.18.1
  get: ^4.6.6
  translator: ^1.0.0
  flutter_localization: ^0.2.0
  easy_localization: ^3.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

  generate: true


  uses-material-design: true


  assets:
    - assets/
    - assets/images/
    - assets/language/


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "/Users/macos/StudioProjects/turnstile_admin/assets/images/logo-light.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "/Users/macos/StudioProjects/turnstile_admin/assets/images/logo-light.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "/Users/macos/StudioProjects/turnstile_admin/assets/images/logo-light.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "/Users/macos/StudioProjects/turnstile_admin/assets/images/logo-light.png"

